# -*- coding: utf-8 -*-
"""keras+cnn_CIFAR-10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UpgNLkkfngK2C03GBl39ut289y8PCgmO
"""

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import numpy as np
import matplotlib.pyplot as plt

from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint

print("TensorFlow version:", tf.__version__)

# ----------------------------
# Dataset CIFAR-10
# ----------------------------
(x_train, y_train), (x_test, y_test) = keras.datasets.cifar10.load_data()

print("Train images:", x_train.shape)  # (50000, 32, 32, 3)
print("Train labels:", y_train.shape)  # (50000, 1)
print("Test  images:", x_test.shape)   # (10000, 32, 32, 3)
print("Test  labels:", y_test.shape)   # (10000, 1)

# labels: (N,1) -> (N,)   una tupla con un solo elemento, una dimensione sola
y_train = y_train.reshape(-1)  # trasforma array in un vettore 1D
y_test  = y_test.reshape(-1)

# Normalizzazione 0-255 -> 0-1
x_train = x_train.astype("float32") / 255.0
x_test  = x_test.astype("float32") / 255.0

print("Train:", x_train.shape, y_train.shape)
print("Test :", x_test.shape, y_test.shape)

#  10 esempi
class_names = [
    "airplane","automobile","bird","cat","deer",
    "dog","frog","horse","ship","truck"
]

plt.figure(figsize=(10, 4))
for i in range(10):
    # subplot(numero_righe, numero_colonne, posizione)
    plt.subplot(2, 5, i+1)
    plt.imshow(x_train[i])  # imshow mostra l'immagine contenuta in x_train[i]
    plt.title(class_names[y_train[i]])
    plt.axis("off")
plt.tight_layout()
plt.show()

#  Modello CNN
model = keras.Sequential([   # i layer vengono applicati uno dopo l'altro
    layers.Input(shape=(32, 32, 3)),  # le immagini in ingresso hanno forma: 32 × 32 pixel 3 canali colore (RGB)

    layers.RandomFlip("horizontal"),
    layers.RandomRotation(0.05),
    layers.RandomZoom(0.1),
    #layers.RandomTranslation(0.1,0.1),

    layers.Conv2D(32, (3, 3), activation="relu", padding="same"), # layer di convoluzione bidimensionale
                                                                  # 32 numero di filtri (feature maps), (3,3) Dimensione del filtro.
                                                                  # padding="same" Serve per mantenere la stessa dimensione spaziale.
    layers.MaxPooling2D((2, 2)),   # Il pooling riduce la dimensione dell'immagine 32 × 32 → 16 × 16

    layers.Conv2D(128, (3, 3), activation="relu", padding="same"),
    layers.MaxPooling2D((2, 2)),   # 16 × 16 → 8 × 8

    layers.Conv2D(128, (3, 3), activation="relu", padding="same"),
    #layers.MaxPooling2D((2, 2)),  # 8 × 8 → 4 × 4

    layers.Flatten(),   # Trasforma il tensore 3D in un vettore da 4 × 4 × 128 in 2048
    layers.Dense(128, activation="relu"),  # ogni neurone è collegato a tutti gli input
    #layers.Dense(64, activation="relu"),  # ogni neurone è collegato a tutti gli input
    layers.Dropout(0.2),   # 30% dei neuroni viene disattivato casualmente
    layers.Dense(10, activation="softmax")  # softmax trasforma i valori in probabilità
])

model.summary()  # Stampa la struttura della rete

# ----------------------------
#  Compile
# ----------------------------
model.compile(
    optimizer="adam",  # come aggiornano i pesi
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

# ----------------------------
#  Callbacks: EarlyStopping + ModelCheckpoint
# ----------------------------
early_stop = EarlyStopping(
    monitor="val_loss",          # guardo la loss di validation
    patience=3,                  # se per 3 epoche non migliora -> stop
    restore_best_weights=True    # rimette i pesi migliori
)

checkpoint = ModelCheckpoint(
    filepath="best_cifar10_model.keras",  # file salvato su disco
    monitor="val_loss",
    save_best_only=True,                 # salva solo se migliora
    verbose=1
)

# ----------------------------
#  Fit
# ----------------------------
history = model.fit(
    x_train, y_train,
    epochs=50,                 # mettiamo alto, early stopping fermerà prima
    batch_size=128,
    validation_split=0.1,
    callbacks=[early_stop, checkpoint],
    verbose=1
)

print("\nChiavi history:", history.history.keys())

# ----------------------------
#  Evaluate sul test (modello in RAM)
# ----------------------------
test_loss, test_acc = model.evaluate(x_test, y_test, verbose=0)
print("\nTEST (model in RAM):")
print("test_loss =", test_loss)
print("test_acc  =", test_acc)

# ----------------------------
#  Carico il best model dal file e rivaluto
# ----------------------------
best_model = keras.models.load_model("best_cifar10_model.keras")
best_test_loss, best_test_acc = best_model.evaluate(x_test, y_test, verbose=0)

print("\nTEST (BEST model da file):")
print("best_test_loss =", best_test_loss)
print("best_test_acc  =", best_test_acc)

#  Predizioni su 10 immagini test
indices = np.random.choice(len(x_test), size=10, replace=False)

plt.figure(figsize=(12, 6))
for i, idx in enumerate(indices):
      # enumerate() restituisce due valori: i   → posizione nel ciclo (0..9)  idx → indice reale dell'immagine nel dataset
    img = x_test[idx]
    true_label = y_test[idx]
    pred = model.predict(img[np.newaxis, ...], verbose=0)[0]
        # modello riceve i dati (batch_size, 32, 32, 3)
        # img[np.newaxis, ...] aggiunge una dimensione davanti.
    pred_label = int(np.argmax(pred))   # argmax trova l'indice del valore massimo
    confidence = float(pred[pred_label] * 100)

    plt.subplot(2, 5, i+1)
    plt.imshow(img)
    color = "green" if pred_label == true_label else "red"
    plt.title(f"True: {class_names[true_label]}\nPred: {class_names[pred_label]} ({confidence:.1f}%)",
              color=color)
    plt.axis("off")

plt.tight_layout()
plt.show()

# ----------------------------
#  Grafici training (loss / acc)
# ----------------------------
plt.figure(figsize=(12, 4))

plt.subplot(1, 2, 1)
plt.plot(history.history["accuracy"], label="train acc")
plt.plot(history.history["val_accuracy"], label="val acc")
# y = history.history["val_accuracy"]
# x = 0,1,2,3,4,...,N  matplotlib crea automaticamente l'asse X (numero di epoca)
plt.title("Accuracy")
plt.legend()
plt.grid(True)

plt.subplot(1, 2, 2)
plt.plot(history.history["loss"], label="train loss")
plt.plot(history.history["val_loss"], label="val loss")
plt.title("Loss")
plt.legend()
plt.grid(True)

plt.show()

print("\nFile salvato:", "best_cifar10_model.keras")