# -*- coding: utf-8 -*-
"""tennis_tournament.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11rWNrCJ4zPXoDUP00uq6Ytr_k7A69cMK
"""

import pandas as pd
import matplotlib.pyplot as plt

import pandas as pd
import io
import requests

# 1. Usiamo un link "Raw" affidabile (GitHub mirror del dataset UCI originale)
# Questo link punta esattamente al file 'AusOpen-men-2013.csv'
url = "https://raw.githubusercontent.com/wadhwasahil/Tennis-Match-Predictor/master/AusOpen-men-2013.csv"

# 2. Leggiamo il CSV direttamente dall'URL
# Se dovesse dare errore di certificato (raro ma possibile nelle reti universitarie),
# aggiungiamo 'storage_options' o usiamo requests, ma di solito basta questo:
try:
    df = pd.read_csv(url)
    print("Dataset scaricato con successo da GitHub!")
except Exception as e:
    print(f"Errore nel download: {e}")
    # Fallback: Se pd.read_csv fallisce direttamente, usiamo requests
    s = requests.get(url).content
    df = pd.read_csv(io.StringIO(s.decode('utf-8')))

# 3. VERIFICA
print(df.head())



# 1. Definiamo le colonne da eliminare (Data Leakage + Target + Stringhe)
colonne_da_eliminare = [
    'Result',                 # Target
    'Player1', 'Player2',     # Stringhe
    'FNL1', 'FNL2',         # Risultato finale set
    'ST1.1', 'ST1.2',         # Game set 1
    'ST2.1', 'ST2.2',         # Game set 2
    'ST3.1', 'ST3.2',         # Game set 3
    'ST4.1', 'ST4.2',         # Game set 4 (già tolte da te)
    'ST5.1', 'ST5.2',         # Game set 5 (già tolte da te)
    'NPW.1','NPW.2',          #net point totali vinti
    'TPW.1', 'TPW.2'          # Punti totali (troppo vicini al risultato)
]

# 2. Creiamo X escludendo queste colonne
# Usiamo errors='ignore' così se alcune le hai già tolte non si blocca
X = df.drop(columns=colonne_da_eliminare, axis=1)

# 3. Il target rimane solo il risultato
y = df['Result']

print("Features rimaste in X:")
print(X.columns.tolist())

print(X.head())
print("------------------")
print(y.value_counts())

print(X.isnull().sum())

#sistemo le colonne NPA mettendo la media dei punti vinti a rete
X['NPA.1'].fillna(X['NPA.1'].mean(), inplace=True)
X['NPA.2'].fillna(X['NPA.2'].mean(), inplace=True)

#metto 0 alle colonne DBA (double faults)
X['DBF.1'] = X['DBF.1'].fillna(0)
X['DBF.2'] = X['DBF.2'].fillna(0)

print(X.isnull().sum())

plt.figure(figsize=(20,10))
X.boxplot()
plt.xticks(rotation=90)
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
import math

df_plot = X.copy()
df_plot["Result"] = y

cols = list(X.columns)
per_fig = 6
n_fig = math.ceil(len(cols) / per_fig)

for f in range(n_fig):
    subset = cols[f*per_fig:(f+1)*per_fig]
    fig, axes = plt.subplots(2, 3, figsize=(16, 8))
    axes = axes.ravel()

    for ax, col in zip(axes, subset):
        sns.boxplot(data=df_plot, x="Result", y=col, ax=ax)
        ax.set_title(col)
        ax.set_xlabel("Result")
        ax.set_ylabel("")

    # spegni assi vuoti
    for ax in axes[len(subset):]:
        ax.axis("off")

    plt.tight_layout()
    plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

# 1. Creiamo un DataFrame temporaneo che unisce X e y
# Questo serve per vedere la correlazione tra le statistiche e la vittoria
df_corr = X.copy()
df_corr['Result'] = y

# 2. Calcoliamo la matrice di correlazione
# Usiamo il metodo di Pearson (standard)
corr_matrix = df_corr.corr()

# 3. Visualizziamo la Heatmap
plt.figure(figsize=(16, 12)) # La facciamo grande per leggere bene i nomi
sns.heatmap(corr_matrix,
            annot=True,      # Mostra i numeri dentro i quadratini
            fmt=".2f",       # Arrotonda a 2 decimali
            cmap='coolwarm', # Colore: rosso (positivo), blu (negativo)
            linewidths=0.5)

plt.title('Correlazione tra Features e Risultato (Australian Open 2013)')
plt.show()

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    stratify=y,
    random_state=42
)

print("Train shape:", X_train.shape)
print("Test shape:", X_test.shape)

#adestramento Decision Tree

from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

tree_model = DecisionTreeClassifier(random_state=42)

tree_model.fit(X_train, y_train)

y_pred = tree_model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))

#confusion matrix

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

cm = confusion_matrix(y_test, y_pred)
print(cm)

disp = ConfusionMatrixDisplay(confusion_matrix=cm)
disp.plot()
plt.title("Decision Tree - Confusion Matrix")
plt.show()

# Classification Report (Precision, Recall, F1)

from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

#ROC Curve e AUC

from sklearn.metrics import roc_curve, roc_auc_score
import matplotlib.pyplot as plt

y_proba = tree_model.predict_proba(X_test)[:, 1]

fpr, tpr, _ = roc_curve(y_test, y_proba)
auc_score = roc_auc_score(y_test, y_proba)

plt.figure()
plt.plot(fpr, tpr, label=f"AUC = {auc_score:.3f}")
plt.plot([0,1],[0,1],"--")
plt.xlabel("FPR")
plt.ylabel("TPR")
plt.title("ROC Curve - Decision Tree")
plt.legend()
plt.show()
print(auc_score)

# 1. IMPORTIAMO TUTTO (Fondamentale su Colab!)
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

plt.figure(figsize=(20, 10))
plot_tree(tree_model,
          feature_names=X_train.columns,
          class_names=['Vince P2', 'Vince P1'],
          filled=True,
          rounded=True,
          fontsize=10)
plt.title("Logica del Decision Tree (Solo Top Features)")
plt.show()

# versione con alcuni features che hanno maggior correlazione positiva e negativa con il target

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, ConfusionMatrixDisplay, roc_curve, roc_auc_score

# --- 1. SELEZIONE TOP FEATURES ---
# Usiamo solo le variabili che la heatmap ci ha indicato come decisive
features_top = ['ACE.1', 'UFE.1', 'BPC.1', 'BPW.1', 'FSW.2', 'SSW.2', 'WNR.2', 'BPC.2', 'BPW.2']

# Creiamo il dataset filtrato
X_top = X[features_top].copy()


# --- 2. SPLIT DEI DATI ---
# Usiamo stratify=y come nel codice della tua collega per mantenere le proporzioni
X_train, X_test, y_train, y_test = train_test_split(
    X_top, y,
    test_size=0.2,
    stratify=y,
    random_state=42
)

# --- 3. ADDESTRAMENTO DECISION TREE ---
# Usiamo max_depth=3 per evitare che l'albero diventi troppo complesso (overfitting)
tree_model_top = DecisionTreeClassifier(max_depth=3, random_state=42)
tree_model_top.fit(X_train, y_train)

# --- 4. PREDIZIONE E VALUTAZIONE ---
y_pred = tree_model_top.predict(X_test)
y_proba = tree_model_top.predict_proba(X_test)[:, 1]

print(f"=== RISULTATI MODELLO TOP FEATURES ===")
print(f"Accuracy: {accuracy_score(y_test, y_pred):.2f}")
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

# --- 5. VISUALIZZAZIONE: CONFUSION MATRIX ---
plt.figure(figsize=(8, 6))
cm = confusion_matrix(y_test, y_pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['Vince P2', 'Vince P1'])
disp.plot(cmap='Blues')
plt.title("Confusion Matrix - Top Features")
plt.show()

# --- 6. VISUALIZZAZIONE: CURVA ROC ---
fpr, tpr, _ = roc_curve(y_test, y_proba)
auc_score = roc_auc_score(y_test, y_proba)

plt.figure(figsize=(8, 6))
plt.plot(fpr, tpr, color='darkorange', label=f"ROC curve (AUC = {auc_score:.2f})")
plt.plot([0, 1], [0, 1], color='navy', linestyle='--')
plt.xlabel("False Positive Rate (Falsi Allarmi)")
plt.ylabel("True Positive Rate (Vittorie Azzeccate)")
plt.title("ROC Curve - Top Features")
plt.legend(loc="lower right")
plt.show()
print(f"SCore finale: {auc_score}")

# --- 7. VISUALIZZAZIONE: L'ALBERO DECISIONALE ---
plt.figure(figsize=(20, 10))
plot_tree(tree_model_top,
          feature_names=features_top,
          class_names=['Vince P2', 'Vince P1'],
          filled=True,
          rounded=True,
          fontsize=10)
plt.title("Logica del Decision Tree (Solo Top Features)")
plt.show()

#proviamo a cambiare modello: Regressione Logistica

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, ConfusionMatrixDisplay

#normalizziamo i dati

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# --- 3. ADDESTRAMENTO ---
log_model= LogisticRegression()
log_model.fit(X_train_scaled, y_train)


# --- 2. PREDIZIONI ---
y_pred = log_model.predict(X_test_scaled)           # Predizione secca (0 o 1)
y_proba = log_model.predict_proba(X_test_scaled)[:, 1] # Probabilità (da 0.0 a 1.0) per la Curva ROC

print(f"Accuratezza: {accuracy_score(y_test, y_pred):.2f}")

# --- 2. REPORT TESTUALE (Tutti gli score: F1, Recall, Precision) ---
print(f"=== RISULTATI MODELLO LOGISTICO (TUTTE LE FEATURES) ===")
print(f"Accuracy: {accuracy_score(y_test, y_pred):.2f}")
print("\nClassification Report:")
print(classification_report(y_test, y_pred))


# - GRAFICO 1: CONFUSION MATRIX ---
plt.figure(figsize=(8, 6))
cm = confusion_matrix(y_test, y_pred)
# Usiamo i nomi delle classi per renderlo leggibile
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['Vince P2', 'Vince P1'])
disp.plot(cmap='Blues', values_format='d')
plt.title("Matrice di Confusione")
plt.show()

# --- 5. GRAFICO 2: CURVA ROC ---
fpr, tpr, _ = roc_curve(y_test, y_proba)
auc_score = roc_auc_score(y_test, y_proba)

plt.figure(figsize=(8, 6))
plt.plot(fpr, tpr, color='darkorange', lw=2, label=f'ROC curve (AUC = {auc_score:.2f})')
plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--') # Linea casuale
plt.xlabel('False Positive Rate (Falsi Allarmi)')
plt.ylabel('True Positive Rate (Vittorie Identificate)')
plt.title('Curva ROC - Regressione Logistica')
plt.legend(loc="lower right")
plt.grid(alpha=0.3)
plt.show()

# --- 3. COEFFICIENTI (Il "cuore" della Regressione Logistica) ---
# Questo grafico DEVE esserci perché spiega il "perché" delle decisioni
coefs = pd.DataFrame({
    'Feature': X_train.columns,
    'Peso': log_model.coef_[0]
}).sort_values(by='Peso', ascending=False)

plt.figure(figsize=(10, 6))
# Usiamo un barplot classico: Rosso = Aiuta P1, Blu = Aiuta P2
colors = ['firebrick' if x > 0 else 'steelblue' for x in coefs['Peso']]
sns.barplot(x='Peso', y='Feature', data=coefs, palette=colors)
plt.axvline(0, color='black', linewidth=1)
plt.title("3. Feature Importance (Pesi della Regressione)", fontsize=14)
plt.xlabel("Impatto sulla probabilità di vittoria (Coefficienti)")
plt.show()

import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, ConfusionMatrixDisplay, roc_curve, roc_auc_score

# --- 1. SELEZIONE FEATURES "RISTRETTE" (Senza BPW per evitare multicollinearità) ---
features_reduced = ['ACE.1', 'UFE.1', 'BPC.1', 'FSW.2', 'SSW.2', 'WNR.2', 'BPC.2']
X_reduced = X[features_reduced].copy()

# --- 2. SPLIT & SCALING (Specifico per queste features) ---
X_train, X_test, y_train, y_test = train_test_split(X_reduced, y, test_size=0.2, stratify=y, random_state=42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# --- 3. ADDESTRAMENTO MODELLO ---
log_model_reduced = LogisticRegression()
log_model_reduced.fit(X_train_scaled, y_train)

# --- 4. PREDIZIONI ---
y_pred = log_model_reduced.predict(X_test_scaled)
y_proba = log_model_reduced.predict_proba(X_test_scaled)[:, 1]

# --- 5. REPORT TESTUALE ---
print(f"=== RISULTATI MODELLO LOGISTICO (FEATURES RISTRETTE) ===")
print(f"Accuracy: {accuracy_score(y_test, y_pred):.2f}")
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

"""L'accuracy è 1! Il modello sembra perfetto! Il motivo non è un overfitting o underfitting ma bensì la dimensione del dataset! Prevedere 26 partite
è molto più facile che prevederne 1000.
"""

# --- 6. GRAFICO 1: CONFUSION MATRIX ì
plt.figure(figsize=(6, 5))
cm = confusion_matrix(y_test, y_pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['Vince P2', 'Vince P1'])
disp.plot(cmap='Blues', values_format='d', colorbar=False)
plt.title("Confusion Matrix (Features Ristrette)")
plt.show()

# --- 7. GRAFICO 2: CURVA ROC
fpr, tpr, _ = roc_curve(y_test, y_proba)
auc_score = roc_auc_score(y_test, y_proba)

plt.figure(figsize=(8, 6))
plt.plot(fpr, tpr, color='darkorange', lw=2, label=f'AUC = {auc_score:.2f}')
plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve (Features Ristrette)')
plt.legend(loc="lower right")
plt.grid(alpha=0.3)
plt.show()

"""Proviamo con uno split del 30-80"""

import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, ConfusionMatrixDisplay, roc_curve, roc_auc_score

# --- 1. SELEZIONE FEATURES "RISTRETTE" (Senza BPW per evitare multicollinearità) ---
features_reduced = ['ACE.1', 'UFE.1', 'BPC.1', 'FSW.2', 'SSW.2', 'WNR.2', 'BPC.2']
X_reduced = X[features_reduced].copy()

# --- 2. SPLIT & SCALING (Specifico per queste features) ---
X_train, X_test, y_train, y_test = train_test_split(X_reduced, y, test_size=0.3, stratify=y, random_state=42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# --- 3. ADDESTRAMENTO MODELLO ---
log_model_reduced = LogisticRegression()
log_model_reduced.fit(X_train_scaled, y_train)

# --- 4. PREDIZIONI ---
y_pred = log_model_reduced.predict(X_test_scaled)
y_proba = log_model_reduced.predict_proba(X_test_scaled)[:, 1]

# --- 5. REPORT TESTUALE ---
print(f"=== RISULTATI MODELLO LOGISTICO (FEATURES RISTRETTE) ===")
print(f"Accuracy: {accuracy_score(y_test, y_pred):.2f}")
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

# --- 6. GRAFICO 1: CONFUSION MATRIX ì
plt.figure(figsize=(6, 5))
cm = confusion_matrix(y_test, y_pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['Vince P2', 'Vince P1'])
disp.plot(cmap='Blues', values_format='d', colorbar=False)
plt.title("Confusion Matrix (Features Ristrette)")
plt.show()